---
- name: Include prompts
  import_tasks: prompts.yml

- block:
    - name: Creating a firewall group
      vultr.cloud.firewall_group:
        api_key: "{{ vultr_api_key }}"
        name: "{{ algo_server_name }}"

    - name: Creating firewall rules
      vultr.cloud.firewall_rule:
        api_key: "{{ vultr_api_key }}"
        group: "{{ algo_server_name }}"
        protocol: "{{ item.protocol }}"
        port: "{{ item.port }}"
        ip_type: "{{ item.ip }}"
        subnet: "{{ item.subnet }}"
        subnet_size: "0"
      loop:
        - { protocol: tcp, port: "{{ ssh_port }}", ip: v4, subnet: 0.0.0.0/0 }
        - { protocol: tcp, port: "{{ ssh_port }}", ip: v6, subnet: "::/0" }
        - { protocol: udp, port: 500, ip: v4, subnet: 0.0.0.0/0 }
        - { protocol: udp, port: 500, ip: v6, subnet: "::/0" }
        - { protocol: udp, port: 4500, ip: v4, subnet: 0.0.0.0/0 }
        - { protocol: udp, port: 4500, ip: v6, subnet: "::/0" }
        - {
            protocol: udp,
            port: "{{ wireguard_port }}",
            ip: v4,
            subnet: 0.0.0.0/0
          }
        - {
            protocol: udp,
            port: "{{ wireguard_port }}",
            ip: v6,
            subnet: "::/0"
          }

    - name: Upload the startup script
      vultr.cloud.startup_script:
        api_key: "{{ vultr_api_key }}"
        name: algo-startup
        script: |
          {{ lookup('template', 'files/cloud-init/base.yml') }}

    - name: Creating a server
      vultr.cloud.instance:
        api_key: "{{ vultr_api_key }}"
        label: "{{ algo_server_name }}"
        startup_script: algo-startup
        hostname: "{{ algo_server_name }}"
        os: "{{ cloud_providers.vultr.os }}"
        plan: "{{ cloud_providers.vultr.size }}"
        region: "{{ algo_vultr_region }}"
        firewall_group: "{{ algo_server_name }}"
        state: started
        tags: ["Environment:Algo"]
        enable_ipv6: true
        backups: false
        activation_email: false
      register: vultr_server

    - set_fact:
        cloud_instance_ip: "{{ vultr_server.vultr_instance.main_ip }}"
        ansible_ssh_user: algo
        ansible_ssh_port: "{{ ssh_port }}"
        cloudinit: true

  environment:
    VULTR_API_CONFIG: "{{ algo_vultr_config }}"
